[package]
name = "tachy-wallet"
version = "0.1.0"
edition = "2021"

[dependencies]
blake3 = "1"
chacha20poly1305 = { version = "0.10", features = ["std", "xchacha20"] }
hkdf = "0.12"
sha2 = "0.10"
rand = "0.8"
rand_core = "0.6"
x25519-dalek = { version = "2", features = ["static_secrets"] }
argon2 = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11"
thiserror = "1.0"
