[package]
name = "tachy-wallet"
version = "0.1.0"
edition = "2021"

[dependencies]
blake3 = "1"
chacha20poly1305 = { version = "0.10", features = ["std", "xchacha20"] }
hkdf = "0.12"
sha2 = "0.10"
rand = "0.8"
rand_core = "0.6"
x25519-dalek = { version = "2", features = ["static_secrets"] }
argon2 = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11"
thiserror = "1.0"

# Additional deps for ZIP-321/324, URIs, storage, encoding
percent-encoding = "2"
base64 = { version = "0.22", default-features = false, features = ["alloc"] }
bech32 = "0.9"
url = { version = "2.5", default-features = false }
sled = "0.34"
time = { version = "0.3", features = ["formatting"] }
hex = "0.4"
once_cell = "1"
regex = "1"
blake2 = "0.10"
blake2b_simd = "1.0"
urlencoding = "2.1"
qrcode = "0.14"
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "ico"] }
serde_json = "1"
zcash_address = "0.5"
ureq = { version = "2.9", features = ["json"] }

[features]
default = []
zip321_crate = ["dep:zip321"]

[dependencies.zip321]
version = "0.1.0"
optional = true

# Serialization for share wrapping (used in export.rs)
bincode = { version = "2.0.0-rc.3", features = ["serde"] }

# Arkworks for Groth16 circuits used by tachystamps.rs
ark-std = "0.4"
ark-ff = "0.4"
ark-ec = "0.4"
ark-relations = "0.4"
ark-serialize = "0.4"
ark-bls12-381 = "0.4"
ark-groth16 = "0.4"
ark-r1cs-std = "0.4"
ark-crypto-primitives = { version = "0.4", default-features = false, features = ["r1cs", "merkle_tree", "crh", "sha256"] }

[lib]
name = "tachy_wallet"
path = "src/lib.rs"
