[package]
name = "tachy-wallet"
version = "0.1.0"
edition = "2021"

[dependencies]
# Note: Removed blake3 - not zk-friendly. Using Poseidon instead.
chacha20poly1305 = { version = "0.10", features = ["std"] }
hkdf = "0.12"
rand = "0.8"
rand_core = "0.6"
x25519-dalek = { version = "2", features = ["static_secrets"] }
argon2 = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11"
thiserror = "1.0"

# Additional deps for ZIP-321/324, URIs, storage, encoding
percent-encoding = "2"
base64 = { version = "0.22", default-features = false, features = ["alloc"] }
bech32 = "0.9"
url = { version = "2.5", default-features = false }
sled = "0.34"
time = { version = "0.3", features = ["formatting"] }
hex = "0.4"
once_cell = "1"
regex = "1"
blake2 = "0.10"
blake2b_simd = "1.0"
urlencoding = "2.1"
qrcode = "0.14"
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "ico"] }
serde_json = "1"
zcash_address = "0.5"
ureq = { version = "2.9", features = ["json"] }

[features]
default = []
zip321_crate = ["dep:zip321"]

[dependencies.zip321]
version = "0.1.0"
optional = true

# Serialization for share wrapping (used in export.rs)
bincode = { version = "2.0.0-rc.3", features = ["serde"] }

# Arkworks for Groth16 circuits & zk-friendly primitives
ark-std = "0.4"
ark-ff = "0.4"
ark-ec = "0.4"
ark-relations = "0.4"
ark-serialize = "0.4"
ark-bls12-381 = "0.4"
ark-groth16 = "0.4"
ark-r1cs-std = "0.4"
ark-crypto-primitives = { version = "0.4", default-features = false, features = ["r1cs", "merkle_tree", "crh"] }

# Pasta curves for Nova (Pallas/Vesta)
ark-pallas = "0.4"
ark-vesta = "0.4"

# Poseidon hash - zk-friendly hash function for Zcash Orchard/Tachyon
poseidon-ark = { version = "0.0.9", features = ["r1cs"] }

# Nova for PCD/recursion over Pasta curves (as per Sean Bowe's vision)
nova-snark = { version = "0.39", default-features = false }

# RedPallas signatures (RedDSA over Pallas) for tachyactions
reddsa = "0.5"

[lib]
name = "tachy_wallet"
path = "src/lib.rs"
